### ISSUE TITLE
fatal error stdarg.h: no such file or directory

### ISSUE THREAD

**Issue by mcbentz** [spacetelescope/jdaviz#694]
Hello,
I am trying to install jdaviz with 'pip install jdaviz' and it keeps failing with:
```
     gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/mbentz/anaconda3/include -arch x86_64 -I/Users/mbentz/anaconda3/include -arch x86_64 -I/Users/mbentz/anaconda3/include/python3.7m -c regions/_compiler.c -o build/temp.macosx-10.9-x86_64-3.7/regions/_compiler.o
   In file included from /Users/mbentz/anaconda3/include/python3.7m/Python.h:97:0,
                     from regions/_compiler.c:1:
    /Users/mbentz/anaconda3/include/python3.7m/bytearrayobject.h:9:10: fatal error: stdarg.h: No such file or directory
     #include <stdarg.h>
              ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1 
```
There are copies of stdarg.h in many directories on my computer, including several associated with CommandLineTools clang and llvm-gcc, so I don't know why it is not being found.

I am working on a Mac OS X 10.12.6 with a fresh installation of anaconda python 3.7.  I uninstalled XCode and command line tools and reinstalled them both (XCode 9.2), and unfortunately that didn't change anything.  I'm not sure what else to try at this point, and would appreciate any help you can give.

Thanks!
Misty Bentz

**Comment by pllim** [comment]
@larrybradley , looks like the failure is from `regions`. Any advise? Thanks!

**Comment by pllim** [comment]
@mcbentz , have you tried create a fresh environment and install your stack there? Anaconda comes with so much baggage that it is hard to debug.

If you get to the point of wanting to reinstall conda itself, I would suggest Miniconda and _never_ install anything into `base` environment; always do your work in another environment that is not `base`.

**Comment by mcbentz** [comment]
Thanks for the suggestion. I just tried creating a new environment and installing jdaviz there.  Unfortunately it crashed with the same error message as before — still failing to find stdarg.h

**Comment by rosteen** [comment]
Silly question, but you activated the environment after creating it right? (don't laugh, I've had that be my problem before...)

It would be useful if you posted the full command history you're running to set up the environment and attempt the install. Some initial thoughts I have are to try doing `pip install jdaviz --no-cache-dir` to force it to re-download all the dependencies in case there's some funny business happening there somehow. I'd also suggest trying to `pip install regions` separately to confirm that the problem is there, not in Jdaviz itself.

Some minor sleuthing on the internet also turns up suggestions to:
- run the GUI version of XCode, which may install some additional things
- run `sudo xcodebuild -license` to make sure it really built, apparently sometimes it will install but need a license agreement or something still with extra permissions
- run `open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg` (I imagine there's a 10.12 equivalent on your machine) to install header files in /usr/include.

I hope some of this is at least slightly useful!

**Comment by mcbentz** [comment]
I was indeed in the activated environment, but I double-checked just in case!  Unfortunately, none of these tips helped.  It was indeed regions that was causing the problem, but installing it on its own with pip didn’t help.  However, I found regions in the anaconda repository, and was able to finally get it installed with 

     conda install -c conda-forge regions 
  
Then I got the bottleneck error, but was able to install that separately as suggested in the Known Issues.  Jdaviz seemed to finish installing at that point, but running jdaviz —help gave me an error with scikit-image (which I thought I had properly installed earlier).  So I uninstalled that and then tried a fresh installation of scikit-image in the new conda environment.  And now FINALLY when I type jdaviz —help, I actually get a help menu.  

I think that means it’s properly installed now?  Thanks for all the help so far!

**Comment by pllim** [comment]
Oh, phew! Yes, regions need C compiler to build from source using `pip` until its maintainer can upload proper wheels for your machine architecture. I am glad the one from conda-forge works!

In general pip installing into a conda env, while convenient and usually gives you new releases faster, comes with risk, so your mileage might vary.

I am glad the installation is completed for you. If you have more problems trying to use Jdaviz, please open new issue(s).

Thank you for your patience!
